### ISSUE TITLE
IRtrans connected but no remotes downloaded

### ISSUE THREAD

**Issue by musca76** [schwarzenbergf/irtrans#108]
Hello, 
First of all thank you very much for your efforts. It would be awesome to integrate IRTrans in my HA. 
I have manage to install the IRTRans repo and now it shows like this:
![image](https://github.com/schwarzenbergf/irtrans/assets/161707380/5a6182be-a8c9-4ccd-a7d1-a9ffb12ac3d9)
The problem is that it showns no remotes from my Irtrans device. 
![image](https://github.com/schwarzenbergf/irtrans/assets/161707380/488f00e0-7da4-41f0-a75e-bc5f10940891)

What I am doing wrong please?
My device is a IRTrans Lan I/O:
![image](https://github.com/schwarzenbergf/irtrans/assets/161707380/9b84a7d7-5ca0-42f6-9eef-cf5b620b7ef7)

Thank you

**Comment by schwarzenbergf** [comment]
I need some more information about your problem.
The easiest way is to go to Settings --> Devices & Services --> iRTrans.
Click on 'Enable debug logging' :
![2024-03-20-171745-settings-home-assistant-screenclip](https://github.com/schwarzenbergf/irtrans/assets/52888262/6e488476-b200-457a-8b46-90be67cd19da)
Now 'Reload' iRTrans (3 dots --> Reload).
After that Disable debug logging and you'll get a download of your LOG-File.
I recommend to open it in an editor. Please look for sensitive information which you don't want to publish to others.
I'm only interested in all entries with [custom_components.irtrans] .
Attach this file here and I guess I'm able to find what is going wrong.

**Comment by musca76** [comment]
2024-03-20 18:35:26.517 DEBUG (MainThread) [custom_components.irtrans] async_unload_entry
2024-03-20 18:35:26.517 DEBUG (MainThread) [custom_components.irtrans] The server closed the connection None
2024-03-20 18:35:26.519 DEBUG (MainThread) [custom_components.irtrans] ->async_setup_entry:Config Entry data (async_setup_entry) {'host': '192.168.1.50', 'port': '21000'} :
2024-03-20 18:35:26.519 DEBUG (MainThread) [custom_components.irtrans] IRTransDataUpdateCoordinator
2024-03-20 18:35:26.519 DEBUG (MainThread) [custom_components.irtrans] hass cfg entry(IRTransDataUpdateCoordinator): 192.168.1.50:21000
2024-03-20 18:35:26.519 DEBUG (MainThread) [custom_components.irtrans] Listener is not running, starting now (DataUpdateCoordinator) ...
2024-03-20 18:35:26.519 DEBUG (MainThread) [custom_components.irtrans] Conneting to 192.168.1.50:21000
2024-03-20 18:35:26.521 DEBUG (MainThread) [custom_components.irtrans] Data sent Aver
:
2024-03-20 18:35:26.521 DEBUG (MainThread) [custom_components.irtrans] Listening on 192.168.1.50:21000
2024-03-20 18:35:26.564 DEBUG (MainThread) [custom_components.irtrans] Data received **00034 VERSION E6.06.30 L1.10.12:
2024-03-20 18:35:26.564 DEBUG (MainThread) [custom_components.irtrans] Version/Firmware ['**00034', 'VERSION', 'E6.06.30 L1.10.12']/E6.06.30 L1.10.12:
2024-03-20 18:35:27.522 DEBUG (MainThread) [custom_components.irtrans] async_update_data before irtrans
2024-03-20 18:35:27.522 DEBUG (MainThread) [custom_components.irtrans] Send irTrans command cmd: Agetremotes  res: REMOTELIST offset: 0
2024-03-20 18:35:27.522 DEBUG (MainThread) [custom_components.irtrans] Data sent Agetremotes 0
:
2024-03-20 18:35:27.580 DEBUG (MainThread) [custom_components.irtrans] Data received **00025 REMOTELIST 0,0,0:
2024-03-20 18:35:27.580 DEBUG (MainThread) [custom_components.irtrans] Response to Agetremotes ['**00025', 'REMOTELIST', '0,0,0']:
2024-03-20 18:35:27.823 ERROR (MainThread) [custom_components.irtrans] Something really wrong happened (api module)! - list index out of range
2024-03-20 18:35:27.824 DEBUG (MainThread) [custom_components.irtrans] async_update_data after irtrans: None
2024-03-20 18:35:27.824 ERROR (MainThread) [custom_components.irtrans] Something really wrong happened (_async_update_data)! - object of type 'NoneType' has no len()
2024-03-20 18:35:27.824 ERROR (MainThread) [custom_components.irtrans] Error fetching irtrans data: 
2024-03-20 18:35:27.824 DEBUG (MainThread) [custom_components.irtrans] Finished fetching irtrans data in 1.305 seconds (success: False)
2024-03-20 18:35:33.144 DEBUG (MainThread) [custom_components.irtrans] ->async_setup_entry:Config Entry data (async_setup_entry) {'host': '192.168.1.50', 'port': '21000'} :
2024-03-20 18:35:33.144 DEBUG (MainThread) [custom_components.irtrans] IRTransDataUpdateCoordinator
2024-03-20 18:35:33.145 DEBUG (MainThread) [custom_components.irtrans] hass cfg entry(IRTransDataUpdateCoordinator): 192.168.1.50:21000
2024-03-20 18:35:33.146 DEBUG (MainThread) [custom_components.irtrans] Get Version msg sent (_async_update_data)
2024-03-20 18:35:33.195 DEBUG (MainThread) [custom_components.irtrans] Data received **00034 VERSION E6.06.30 L1.10.12:
2024-03-20 18:35:33.196 DEBUG (MainThread) [custom_components.irtrans] Version/Firmware ['**00034', 'VERSION', 'E6.06.30 L1.10.12']/E6.06.30 L1.10.12:
2024-03-20 18:35:34.147 DEBUG (MainThread) [custom_components.irtrans] Finished fetching irtrans data in 1.002 seconds (success: True)
2024-03-20 18:35:34.147 DEBUG (MainThread) [custom_components.irtrans] Triggers(device_trigger): irtrans, sensor, [{'platform': 'device', 'device_id': 'c8835587da6ccb6775f729cbf4efb892', 'domain': 'irtrans', 'entity_id': 'sensor.irtrans_sensor', 'type': 'remote_pressed', 'event_data': {'remote': ['first', 'second', 'third'], 'button': ['0', '1', '2', '3', '4', '5', 'vol+', 'vol-', 'ch+', 'ch-']}}]
2024-03-20 18:35:34.147 DEBUG (MainThread) [custom_components.irtrans] async_setup_entry--> c8835587da6ccb6775f729cbf4efb892 / [{'platform': 'device', 'device_id': 'c8835587da6ccb6775f729cbf4efb892', 'domain': 'irtrans', 'entity_id': 'sensor.irtrans_sensor', 'type': 'remote_pressed', 'event_data': {'remote': ['first', 'second', 'third'], 'button': ['0', '1', '2', '3', '4', '5', 'vol+', 'vol-', 'ch+', 'ch-']}}] / sensor.irtrans_sensor
2024-03-20 18:35:34.148 DEBUG (MainThread) [custom_components.irtrans] IRTRANS Sensor platform setup: 
2024-03-20 18:35:34.148 DEBUG (MainThread) [custom_components.irtrans] Creating services.yaml ...
2024-03-20 18:35:34.149 DEBUG (MainThread) [custom_components.irtrans] Finished writing services.yaml

**Comment by musca76** [comment]
Thank you for the detailed explanations - very easy to follow
I posted above the logs.
Appreciate your help.

**Comment by schwarzenbergf** [comment]
OK, this looks not so bad. Connection is established and Version information has been successfully received.
But there are obviously no flashed Remotes in the device.
The API command to get the Remotes is:

> Agetremotes 0

and the answer is

> **00025 REMOTELIST 0,0,0

which means, there are no programmed IR Remotes in the device database.
You can check this manually by your own for example with _putty_ (or something similar):
With _putty_ just open a **raw** connection to your IRTrans device : 

> Host Name: 192.168.1.50 Port: 21000

You will see nothing. Just enter 

> Agetremotes `ENTER`

you should get the above shown answer.

Please check that you have flashed your database to the device. I recommend to do it again.
Make sure that you have selected the Remote for flashing (in your case _sonypc_). This is done by _right click_ on _sonypc_ and choosing _Select_. The entry should be highlighted after that.
Now flash the database to the device:

![image](https://github.com/schwarzenbergf/irtrans/assets/52888262/96b39f4e-21c7-46e0-ad8c-16f2b6dcc599)


I'm not so familiar with the different versions of IRTrans devices. This integration only supports IRTrans devices **with IR Device Database**. I think the LAN I/O device has this support, but please check this as well.

**Comment by musca76** [comment]
:)))
I can't thank you enough.
Problem solved. 
The thing was that uploading the remotes to IRTrans Database was not very clear for me.  I never "select" the remotes and I never got any error message from de device sayng no remotes are uploaded. 
Now everything works as it supposed to. I managed to create a button on HA that turns on/off different equipment via IRtrans. 
One more thig will be very useful: to be able to control the led/device id/bus IRtrans uses to send this commands. 
![image](https://github.com/schwarzenbergf/irtrans/assets/161707380/9ff38c90-dcd9-4e15-916a-92afafe8f4a7)
I have several Daikin A/Cs and all run on the same ir code. I have them wired to different IRTrans leds so I can control separately but I do not know how to do it from HA.

I really want to give you thumb up for the quality of your instructions - I never got so clear and easy to follow guide. So easy for me to understand. 
It will be my pleasure to buy you a beer somehow - just let me know how. 
Cheers, 
Andrei

**Comment by schwarzenbergf** [comment]
Hi Andrei,
I think I understood what you need. Unfortunately those parameters (LED, Device ID, Bus ID) are not supported yet.
You are the first who came up with this.
I will have a look into that. Should be not so difficult but requires some reprogramming of the integration.
It'll take some time (hopefully not more than 1-2 weeks).

No need for a beer - but thank you. Give the integration a Star in HACS, this is enough.

Frank

**Comment by schwarzenbergf** [comment]
Hi Andrei,
I will soon (probably tomorrow) publish a new version which allows to choose LED, BUS and MASK parameters (probably only LED makes sense).
Please test it and open a new issue if there are problems.
I close this issue now.

**Comment by musca76** [comment]
Thank you very much. Looking forward to test it.
Have a nice weekend,

**Comment by musca76** [comment]
Thank you for the new version.
I am back home now and I had time to fully test it.
I can now select Led, Bus and mask but Irtrans sends commands to All leds,
buses and Mask no matter what I choose.
If I select the led from here (IRTrans server on my pc):
[image: image.png]
only all/external and led 4 works.
I HA no matter what I choose the signal is sent to all leds.

Any idea why?

Thank you very much,
Andrei

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by schwarzenbergf** [comment]
I published a new version (v1.11). Please try it. LED should work, I tested internal (i), external (e) and both (b). My unit does not support LED numbers, so I cannot test this.
I have also just one unit, so BUS seems to be ignored.
MASK probably makes no sense, it works only via serial bus (provided my understanding is correct).

**Comment by musca76** [comment]
Hello,
Good news and bad news :))
The good news is that led (i, e, all and 1-4) work perfectly. Bus and mask
I was not able to test.
Now the bad news:
1 hour after I was happy I have updated the HA  both core and supervision.
After that I was not able to find the IRTrans service anymore.
For a strange reason the RTrans: send_irtrans_ir_command service has been
transformed to
irtrans: send_irtrans_ir_command_RemoteName.
This means instead of 1 service I have now 3 (the number of my remotes).
Normally this should not be a problem but the situation gets even more
complicated: when I select the service the buttons for device, area, led
and mask do not appear anymore.
Instead I get this service data field:
[image: image.png]

Normally this should not be a problem - it is quite easy to understand. But
what I found later is that it is not consistent. When you are trying to do
the same thing in automations you get errors. Same goes for helpers. You
have to fiddle with YAML and not always get the correct reaction.
[image: image.png]
[image: image.png]
[image: image.png]


My knowledge in this field is limited - please excuse me if I am stupid.
Thanks again,

**Comment by schwarzenbergf** [comment]
Unfortunately I cannot see your attached pictures.
It is correct that you have for every Remote a dedicated service:
**send_irtrans_ir_command**__RemoteName_
As I said, I cannot see your pictures. But if you see a _service data _field__ may be your are in YAML Mode?

As a last resort please just uninstall the integration and reinstall it. This should be no problem.
Let me know the result and try to attach pictures in a way that I can see them (I see only _[image: image.png]_ for all your pictures).

**Comment by musca76** [comment]
Sorry for the picture problem. I was reply from my email and seemed ok.

I have reinstall it. 
It got worse. 

Here what I got now:
![1Screenshot 2024-04-08 201859](https://github.com/schwarzenbergf/irtrans/assets/161707380/773f05fb-b7d8-4e16-ace0-1ebbebc76de6)


If I click on Go to YAML I get: 
![2Screenshot 2024-04-08 204009](https://github.com/schwarzenbergf/irtrans/assets/161707380/9256e1a0-e042-4f75-9d59-66eae912b9a8)

I have tried to input something like this: 

![3Screenshot 2024-04-08 204307](https://github.com/schwarzenbergf/irtrans/assets/161707380/9f09803d-a541-420a-aa2d-756f32598402)


Now (after re-install) nothing works anymore.

**Comment by musca76** [comment]
It used to work as you described before. But after the HA update (I am
guessing here) IRTrans: Send IRTrans IR Command is not available anymore.
Only services like:  iRTrans: send_irtrans_ir_command_daikin o  (with the
remote name at the end.
This means I cannot select device (irtrans sensor) and neigher area, entity
and label.
Same goes for Button card or for call service.

**Comment by musca76** [comment]
It used to work as you described before. But after the HA update (I am
guessing here) IRTrans: Send IRTrans IR Command is not available anymore.
Only services like:  iRTrans: send_irtrans_ir_command_daikin o  (with the
remote name at the end).
This means I cannot select device (irtrans sensor) and neigher area, entity
and label.
Same goes for Button card or for call service.
Here are some screen shots:
![10Screenshot 2024-04-09 124946](https://github.com/schwarzenbergf/irtrans/assets/161707380/fc88fb53-f306-4ce4-b781-52f0b3c10c9b)
![11Screenshot 2024-04-09 124946](https://github.com/schwarzenbergf/irtrans/assets/161707380/33501fb8-cf4c-45f3-a44b-417dd5aa1510)

![12Screenshot 2024-04-09 125312](https://github.com/schwarzenbergf/irtrans/assets/161707380/e115134c-f74b-490b-a5e9-3ec740e37423)
![13Screenshot 2024-04-09 125344](https://github.com/schwarzenbergf/irtrans/assets/161707380/799a0438-c90d-400f-896c-27d519751bbe)

Anyway, after I received your earlier explanation I have tried to manually write the code in YAML (just learned what is YAML 2 days ago :)).
 IT WORKED. Indeed the missing entity id (sensor.irtrans_sensor) was the problem. 
It would have been much easier to be able to select it in UI like before but important for me is the functionality not the form. I can live with that. One thing I have noticed is all the parameters (remote, ir_cmd and some of led (i and e)) are without quote """. If you use a led number (1,2,3 etc ) you have to but it between quotes. Probably your code expects a chat and this is how to tell it to interpret the number as a char.

**Comment by musca76** [comment]
I am trying to understand what happened.
As I told you before everything was working fine as you suggested and I was able to select in UI the device, area etc. 
I had like 5 buttons that were sending ir signals with no problem. 
Now I have to manually edit all of them in YAML and input the "entity_id: sensor.irtrans_sensor" to make them work again. 

And I just realize the following:
1. none of the buttons were having the entity_id before although all of then were working fine. 
2. all of then have  device_id: c8835587da6ccb6775f729cbf4efb892
3. If I replace the device_Id with entity_id averything works fine as before. 
Does this make any sense to you?

**Comment by schwarzenbergf** [comment]
There has nothing changed with respect to the service calls. It is the case from the beginning that there is for every Remote a dedicated service call. I cannot really judge what you did before and why it worked, but it was not correct. The correct way is what I described.

It is essential to use the _entity_id_ and not the _Device ID_, otherwise it won't work as expected.

I do not understand why the fields for detailed configuration in your Developer Tools (and in the Button Card config) are missing.
May be it has something to do with the _Advanced mode_? 
Do you have _Advanced mode_ enabled in your Profile?

![image](https://github.com/schwarzenbergf/irtrans/assets/52888262/a78e1cdf-7605-4091-b4ea-a0292b34fe10)

But this makes not much sense.

May be you should again completely uninstall IRTrans and then look in this directory that nothing with 'irtrans' has been left:
_/config/custom_components/_
If there is still a directory 'irtrans' then delete it before installing IRTrans again.

**Comment by schwarzenbergf** [comment]
There is a file _services.yaml_ in your HA config directory under _custom_components/irtrans_.
Could you attach it here? Actually there are all the Services descriptions including the options.
Just to check that this is all OK.

**Comment by musca76** [comment]
`send_irtrans_ir_command_daikin o:
  name: Send IRTrans IR Command
  description: Send for daikin o Remote an IR command
  target:
  fields:
    remote:
      name: Remote
      description: daikin o
      required: true
      selector:
        select:
          options:
            - daikin o
    ir_cmd:
      name: IR Command
      description: IR Command to send to daikin o
      required: true
      example: "vol+"
      selector:
        select:
          options:
            - "swing on"
            - "swing off"
            - "swing"
            - "off"
            - "on 19c fana mode*"

    led:
      name: LED
      description: Which LED to use for transmitting IR Command
      required: false
      example: "i"
      selector:
        select:
          options:
            - "i"
            - "e"
            - "b"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    bus:
      name: BUS
      description: The IRTrans Ethernet module that you want to send the command
      required: false
      example: "0"
      selector:
        select:
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    mask:
      name: MASK
      description: This sets the net mask that chooses the modules connected through the IRTrans Serial Bus
      required: false
      example: "256"
      selector:
        number:
          min: 0
          max: 65535
          mode: box
send_irtrans_ir_command_daikin x:
  name: Send IRTrans IR Command
  description: Send for daikin x Remote an IR command
  target:
  fields:
    remote:
      name: Remote
      description: daikin x
      required: true
      selector:
        select:
          options:
            - daikin x
    ir_cmd:
      name: IR Command
      description: IR Command to send to daikin x
      required: true
      example: "vol+"
      selector:
        select:
          options:
            - "off"
            - "on 19c fana mode*"

    led:
      name: LED
      description: Which LED to use for transmitting IR Command
      required: false
      example: "i"
      selector:
        select:
          options:
            - "i"
            - "e"
            - "b"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    bus:
      name: BUS
      description: The IRTrans Ethernet module that you want to send the command
      required: false
      example: "0"
      selector:
        select:
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    mask:
      name: MASK
      description: This sets the net mask that chooses the modules connected through the IRTrans Serial Bus
      required: false
      example: "256"
      selector:
        number:
          min: 0
          max: 65535
          mode: box
send_irtrans_ir_command_sonypc:
  name: Send IRTrans IR Command
  description: Send for sonypc Remote an IR command
  target:
  fields:
    remote:
      name: Remote
      description: sonypc
      required: true
      selector:
        select:
          options:
            - sonypc
    ir_cmd:
      name: IR Command
      description: IR Command to send to sonypc
      required: true
      example: "vol+"
      selector:
        select:
          options:
            - "mute"
            - "on/off"
            - "vol-"
            - "vol+"

    led:
      name: LED
      description: Which LED to use for transmitting IR Command
      required: false
      example: "i"
      selector:
        select:
          options:
            - "i"
            - "e"
            - "b"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    bus:
      name: BUS
      description: The IRTrans Ethernet module that you want to send the command
      required: false
      example: "0"
      selector:
        select:
          options:
            - "0"
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
            - "6"
            - "7"
            - "8"
    mask:
      name: MASK
      description: This sets the net mask that chooses the modules connected through the IRTrans Serial Bus
      required: false
      example: "256"
      selector:
        number:
          min: 0
          max: 65535
          mode: box
`

**Comment by schwarzenbergf** [comment]
Everything seems to be there.

Just another idea:

- Clear your Browser cache
- Use another Browser
- Use another Device
- Try the Mobile App

**Comment by musca76** [comment]
Ufff - I am getting crazy here :))

Cleared cash
used Edge browser
Tried on mobile 
Uninstalled completely (no irtrans folder in custom components).
I am trying a different approach now:
Let's create an automation. 
![Screenshot 2024-04-09 195736](https://github.com/schwarzenbergf/irtrans/assets/161707380/9af8a333-d4ad-436d-a8d1-f9a2e98b9ace)

I do not get to choose the options. Nor the YAML code. 
When I press save I get: 
![Screenshot 2024-04-09 200236](https://github.com/schwarzenbergf/irtrans/assets/161707380/b5dfca60-3251-4858-9d90-12059b3b630c)

Press 3 dots > Edit in YAML 
I input: 
![Screenshot 2024-04-09 200452](https://github.com/schwarzenbergf/irtrans/assets/161707380/8fb97f04-60a1-4d1d-9d60-9a5ecfd50256)

and I get this error: 
![Screenshot 2024-04-09 200523](https://github.com/schwarzenbergf/irtrans/assets/161707380/e4c769e0-129c-40a2-b511-3d6b68e1c5c2)


I also tried: 

![Screenshot 2024-04-09 201032](https://github.com/schwarzenbergf/irtrans/assets/161707380/dfd1b240-aed9-4502-931f-2513892dcc81)

And also as a service: 
![1Screenshot 2024-04-09 201114](https://github.com/schwarzenbergf/irtrans/assets/161707380/dca057ee-d0d2-4cd4-a939-bd9a9c87a0e4)

**Comment by musca76** [comment]
F#*#*@#*$@#

Problem solved. 

Everything is back to normal 
Nothing to do with HA
The remotes, comands and everything else are not allowed to have spaces. 
2 of my remotes were daikin x and daikin o
This completely messed up everything. 
Flashed the IRTrans. Upload sonypc and daikin_x remotes and everything works as it should. 
Shame on me - I wasted you time. Apologies. 
Thank you for the beautiful integration. 

![image](https://github.com/schwarzenbergf/irtrans/assets/161707380/20e1c90f-1cc9-4d31-92bf-92b1bcf929b1)

**Comment by schwarzenbergf** [comment]
Oh yes, I didn't notice that there where spaces in the Remote names again. I fixed this already on the 'Input' side (when reading from IRTrans device). But the Services obviously have the same problem (output to HA).
Anyway, I'm not sure whether I can do something on my side, but I will have a look into that (just to avoid future problems).
But in general I recommend in the context of computers and keywords or names, try to avoid spaces, they always  tend to make trouble.
Good job from your side. I hope it will work now for you as expected.
I close this issue now.

**Comment by musca76** [comment]
Hello Frank,
I am experimenting again with problems with the Irtrans integration in HA.
It was working fine. I have modified some remotes in irtrans and I have
noticed the integration was not uploading the remotes anymore.
I have even deleted some remotes in Irtrans but they were still present in
HA. But the old remotes were still working in HA.
I have deleted the integration and re-install it.
After I have added the device (ip and port)  I got an "Failed to set up:
Check the logs error. "
Any idea what is going on ?

Many thanks as usual,
Andrei
[image: image.png]

**Comment by musca76** [comment]
I forgot to attach the error I found in logs:
[image: image.png]

**Comment by schwarzenbergf** [comment]
Hi Andrei,
I'm currently on vacation. I will be back in about one week and will then take care of your issue.

**Comment by musca76** [comment]
Thank you very much Frank.
Enjoy your holiday,
A

**Comment by musca76** [comment]
Hello Frank,
I hope you had a beautiful vacation.
I do not want to be a nuisance, just to remind you of my problem.
I know you do it in your free time and I highly appreciate your help,
All the best,
Andrei

**Comment by schwarzenbergf** [comment]
Hi Andrei,
Yes, I'm back and started to look into that.
Unfortunately I cannot see the attached image with the error log.
Could you please try to send the error log again?

**Comment by musca76** [comment]
Thanks for helping me.
I have attached the image one more time to this email.
Let me know if you do not get it.

**Comment by schwarzenbergf** [comment]
Sorry, now there is no attachment at all. In the last comment I saw at  least '[image: image.png]'.

**Comment by musca76** [comment]
still no?

**Comment by schwarzenbergf** [comment]
Sorry, no attachment in the E-Mail and nothing to see here on GitHub.
We had the same problem at the beginning. I do not know what you did but those times it worked finally.
I prefer to have the conversation here in GitHub because it is a complete documentation and history.
So, try to comment and attach in GitHub, this should work.

**Comment by musca76** [comment]
sure. I have opened a github bug ticket.
